//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeneracionIngresosEntities : DbContext
    {
        public GeneracionIngresosEntities()
            : base("name=GeneracionIngresosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAccesoRol> tbAccesoRol { get; set; }
        public virtual DbSet<tbPermisos> tbPermisos { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbRolesUsuario> tbRolesUsuario { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }
        public virtual DbSet<tbPrograma> tbPrograma { get; set; }
        public virtual DbSet<tbRubroEmpresa> tbRubroEmpresa { get; set; }
        public virtual DbSet<tbTipoSeguimiento> tbTipoSeguimiento { get; set; }
        public virtual DbSet<tbTipoTaller> tbTipoTaller { get; set; }
        public virtual DbSet<tbBeneficiarios> tbBeneficiarios { get; set; }
        public virtual DbSet<tbCapacitacion> tbCapacitacion { get; set; }
        public virtual DbSet<tbCapacitacion_Beneficiarios> tbCapacitacion_Beneficiarios { get; set; }
        public virtual DbSet<tbCapacitador> tbCapacitador { get; set; }
        public virtual DbSet<tbCentroAlcance> tbCentroAlcance { get; set; }
        public virtual DbSet<tbEmpleabilidad> tbEmpleabilidad { get; set; }
        public virtual DbSet<tbEmprendimiento> tbEmprendimiento { get; set; }
        public virtual DbSet<tbEmpresa> tbEmpresa { get; set; }
        public virtual DbSet<tbSeguimiento> tbSeguimiento { get; set; }
        public virtual DbSet<tbEventos> tbEventos { get; set; }
        public virtual DbSet<tbUsuariosLinea> tbUsuariosLinea { get; set; }
    }
}
