//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBeneficiarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbBeneficiarios()
        {
            this.tbCapacitacion_Beneficiarios = new HashSet<tbCapacitacion_Beneficiarios>();
            this.tbEmpleabilidad = new HashSet<tbEmpleabilidad>();
            this.tbEmprendimiento = new HashSet<tbEmprendimiento>();
            this.tbSeguimiento = new HashSet<tbSeguimiento>();
        }
    
        public int ben_Id { get; set; }
        public string ben_Identificacion { get; set; }
        public string ben_Nombres { get; set; }
        public string ben_Apellidos { get; set; }
        public string ben_Telefono { get; set; }
        public string ben_CorreoElectronico { get; set; }
        public string mun_Id { get; set; }
        public string ben_Direccion { get; set; }
        public string ben_Sexo { get; set; }
        public System.DateTime ben_FechaNacimiento { get; set; }
        public string ben_NivelAcademico { get; set; }
        public bool ben_Amigrado { get; set; }
        public bool ben_TieneIntenciones { get; set; }
        public bool ben_ExMiembroPandilla { get; set; }
        public bool ben_EsVoluntario { get; set; }
        public Nullable<int> cda_Id { get; set; }
        public string ben_TipoBeneficiario { get; set; }
        public int prog_Id { get; set; }
        public int ben_UsuarioCrea { get; set; }
        public System.DateTime ben_FechaCrea { get; set; }
        public Nullable<int> ben_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> ben_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbMunicipios tbMunicipios { get; set; }
        public virtual tbPrograma tbPrograma { get; set; }
        public virtual tbCentroAlcance tbCentroAlcance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCapacitacion_Beneficiarios> tbCapacitacion_Beneficiarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmpleabilidad> tbEmpleabilidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmprendimiento> tbEmprendimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSeguimiento> tbSeguimiento { get; set; }
    }
}
