//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCapacitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCapacitacion()
        {
            this.tbCapacitacion_Beneficiarios = new HashSet<tbCapacitacion_Beneficiarios>();
        }
    
        public int cap_Id { get; set; }
        public int tptal_Id { get; set; }
        public int cdor_Id { get; set; }
        public System.DateTime cap_Fecha { get; set; }
        public string cap_Lugar { get; set; }
        public int cap_UsuarioCrea { get; set; }
        public System.DateTime cap_FechaCrea { get; set; }
        public Nullable<int> cap_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cap_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbTipoTaller tbTipoTaller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCapacitacion_Beneficiarios> tbCapacitacion_Beneficiarios { get; set; }
        public virtual tbCapacitador tbCapacitador { get; set; }
    }
}
