//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCapacitador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCapacitador()
        {
            this.tbCapacitacion = new HashSet<tbCapacitacion>();
        }
    
        public int cdor_Id { get; set; }
        public string cdor_Identificacion { get; set; }
        public string cdor_Nombres { get; set; }
        public string cdor_Apellidos { get; set; }
        public string cdor_Telefono { get; set; }
        public string cdor_CorreoElectronico { get; set; }
        public string cdor_Direccion { get; set; }
        public string cdor_Sexo { get; set; }
        public Nullable<System.DateTime> cdor_FechaNacimiento { get; set; }
        public bool cdor_EsActivo { get; set; }
        public int cdor_UsuarioCrea { get; set; }
        public System.DateTime cdor_FechaCrea { get; set; }
        public Nullable<int> cdor_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cdor_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCapacitacion> tbCapacitacion { get; set; }
    }
}
