//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCapacitacion_Beneficiarios
    {
        public int capben_Id { get; set; }
        public Nullable<int> cap_Id { get; set; }
        public Nullable<int> tptal_Id { get; set; }
        public Nullable<int> even_Id { get; set; }
        public Nullable<int> ben_Id { get; set; }
    
        public virtual tbTipoTaller tbTipoTaller { get; set; }
        public virtual tbBeneficiarios tbBeneficiarios { get; set; }
        public virtual tbCapacitacion tbCapacitacion { get; set; }
        public virtual tbEventos tbEventos { get; set; }
    }
}
