//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCentroAlcance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCentroAlcance()
        {
            this.tbBeneficiarios = new HashSet<tbBeneficiarios>();
        }
    
        public int cda_Id { get; set; }
        public string cda_Descripcion { get; set; }
        public string mun_Id { get; set; }
        public bool cda_EsAcademia { get; set; }
        public string cda_TipoAcademia { get; set; }
        public int cda_UsuarioCrea { get; set; }
        public System.DateTime cda_FechaCrea { get; set; }
        public Nullable<int> cda_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> cda_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbMunicipios tbMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBeneficiarios> tbBeneficiarios { get; set; }
    }
}
