//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleabilidad
    {
        public int empl_Id { get; set; }
        public int ben_Id { get; set; }
        public int emp_Id { get; set; }
        public bool empl_EsAcademia { get; set; }
        public System.DateTime empl_FechaIngreso { get; set; }
        public string empl_CargoDesempeña { get; set; }
        public int empl_UsuarioCrea { get; set; }
        public System.DateTime empl_FechaCrea { get; set; }
        public Nullable<int> empl_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> empl_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbBeneficiarios tbBeneficiarios { get; set; }
        public virtual tbEmpresa tbEmpresa { get; set; }
    }
}
