//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEvaluaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEvaluaciones()
        {
            this.tbPreguntas = new HashSet<tbPreguntas>();
        }
    
        public int evac_Id { get; set; }
        public string evac_Descripcion { get; set; }
        public string evac_TipoEvaluacion { get; set; }
        public bool evac_Estado { get; set; }
        public int evac_UsuarioCrea { get; set; }
        public System.DateTime evac_FechaCrea { get; set; }
        public Nullable<int> evac_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> evac_FechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPreguntas> tbPreguntas { get; set; }
    }
}
