//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPermisos
    {
        public int permi_Id { get; set; }
        public string permi_Pantalla { get; set; }
        public string permi_Referencia { get; set; }
        public bool permi_Estado { get; set; }
        public int permi_UsuarioCrea { get; set; }
        public System.DateTime permi_FechaCrea { get; set; }
        public Nullable<int> permi_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> permi_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
