//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPreguntas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbPreguntas()
        {
            this.tbRespuestas = new HashSet<tbRespuestas>();
        }
    
        public int preg_Id { get; set; }
        public string preg_Descripcion { get; set; }
        public int evac_Id { get; set; }
        public bool preg_Estado { get; set; }
        public int preg_UsuarioCrea { get; set; }
        public System.DateTime preg_FechaCrea { get; set; }
        public Nullable<int> preg_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> preg_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbEvaluaciones tbEvaluaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbRespuestas> tbRespuestas { get; set; }
    }
}
