//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRespuestas
    {
        public int resp_Id { get; set; }
        public string resp_Descripcion { get; set; }
        public bool resp_Estado { get; set; }
        public int preg_Id { get; set; }
        public int resp_UsuarioCrea { get; set; }
        public System.DateTime resp_FechaCrea { get; set; }
        public Nullable<int> resp_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> resp_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbPreguntas tbPreguntas { get; set; }
    }
}
