//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSeguimiento
    {
        public int seg_Id { get; set; }
        public int ben_Id { get; set; }
        public Nullable<System.DateTime> seg_Fecha { get; set; }
        public string seg_Observaciones { get; set; }
        public int tpseg_Id { get; set; }
        public int seg_UsuarioCrea { get; set; }
        public System.DateTime seg_FechaCrea { get; set; }
        public Nullable<int> seg_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> seg_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
        public virtual tbTipoSeguimiento tbTipoSeguimiento { get; set; }
        public virtual tbBeneficiarios tbBeneficiarios { get; set; }
    }
}
