//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUNADEH_PLATAFORMAVIRTUAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuariosLinea
    {
        public int usul_Id { get; set; }
        public string usul_Identidad { get; set; }
        public string usul_Nombres { get; set; }
        public string usul_Apellidos { get; set; }
        public string usul_CorreoElectronico { get; set; }
        public byte[] usul_Password { get; set; }
        public bool usul_Estado { get; set; }
        public string usul_Status { get; set; }
        public int usul_UsuarioCrea { get; set; }
        public System.DateTime usul_FechaCrea { get; set; }
        public Nullable<int> usul_UsuarioModifica { get; set; }
        public Nullable<System.DateTime> usul_FechaModifica { get; set; }
    
        public virtual tbUsuarios tbUsuarios { get; set; }
        public virtual tbUsuarios tbUsuarios1 { get; set; }
    }
}
